[package]
name = "cdsd"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = "0.27.0"
csv = "1.4.0"
clap = { version = "4.6.1", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["blocking"] }
log = "0.4.30"
simplelog = "0.12.2"
thiserror = "2.0.18"
anyhow = "1.0.102"

[dev-dependencies]
mockall = "0.14.0"
tempfile = "3.27.0"
mockito = { version = "1.7.2" }
rstest = "0.26.1"
